### ISSUE TITLE
CSADigitizer: Wrong time when setting ToA binsize (?)

### ISSUE THREAD

**Issue by stephanlachnit** [allpix-squared/allpix-squared#28]
I've looked a little bit in the code of the ToA / ToT measurement, and something seems off to me. I'm not sure if this is just me being stupid or if there is actually something wrong.

Looking at: https://github.com/allpix-squared/allpix-squared/blob/2005e9f71f3944c0eecc9b1c54080df0110bd72e/src/modules/CSADigitizer/CSADigitizerModule.cpp#L342

We seem to add the local time, the global time, and the charge in the vector. "charge" in this case can also mean ToT signal (or rather TS2, I'll explain later). Everything is fine there. However, time can also mean the ToA signal in clock cycles. That in itself is also fine, if we know that. However, adding `time` to `pixel_charge.getGlobalTime()` doesn't make sense in that case. We add clock cycles to something which is in nanoseconds. Am I missing something, or is this wrong?

A fix could be multiplying the `time` with the bin size here: https://github.com/allpix-squared/allpix-squared/blob/2005e9f71f3944c0eecc9b1c54080df0110bd72e/src/modules/CSADigitizer/CSADigitizerModule.cpp#L321

Related to this:
I realized that the signal only is the "ToT", but that actually isn't the time over threshold, but rather only the second timestamp (that's why I prefer TS2 / TS1 to avoid misconceptions). A proper ToT would be `TS2-TS1`. Of course, this would mean that we would need to add some code that handles different clock sizes. One idea would be simply to do `TS2_signal * TS2_clk - ToA_signal * ToA_clk`, which then wouldn't return the signal in clock cycles but the resulting time from it.

I see that this would drastically change the way how this would work, and this can be relatively easy achieved by analysis after the run. Let me know what you think about this.

**Comment by simonspa** [comment]
Hi @stephanlachnit 

there are a few things in this issue, let's address them one-by-one:

* "charge is only TS2": I don't think this assessment is correct. If you check the relevant code in `get_tot` you will see that [we start counting clock cycles only after threshold crossing](https://github.com/allpix-squared/allpix-squared/blob/2005e9f71f3944c0eecc9b1c54080df0110bd72e/src/modules/CSADigitizer/CSADigitizerModule.cpp#L398-L400) with the additional refinement of starting only at the next clock edge. This calculation I think is correct as it is.
* "time means clock cycles": This is intentional. If ToT and/or ToA are enabled, the module is supposed to produce output that mimics what a chip would provide, i.e. just providing a clock cycle count for the two values `time` and `charge`. So also here I think the definition as is is correct. Maybe we need to refine the README to explain this in more detail.
* "global time definition is odd": This indeed is correct, mixing time with clock cycles is not a nice thing to do. :) So that line should actually read
    ```cpp
    hits.emplace_back(pixel, time, pixel_charge.getGlobalTime() + std::get<2>(arrival), charge, &pixel_charge);
    ```

Do you agree?
Did I miss anything?

/Simon

**Comment by stephanlachnit** [comment]
>     * "charge is only TS2": I don't think this assessment is correct. If you check the relevant code in `get_tot` you will see that [we start counting clock cycles only after threshold crossing](https://github.com/allpix-squared/allpix-squared/blob/2005e9f71f3944c0eecc9b1c54080df0110bd72e/src/modules/CSADigitizer/CSADigitizerModule.cpp#L398-L400) with the additional refinement of starting only at the next clock edge. This calculation I think is correct as it is.

Ah thanks yes of course, sorry for that.

>     * "time means clock cycles": This is intentional. If ToT and/or ToA are enabled, the module is supposed to produce output that mimics what a chip would provide, i.e. just providing a clock cycle count for the two values `time` and `charge`. So also here I think the definition as is is correct. Maybe we need to refine the README to explain this in more detail.

Yes this makes perfect sense. I guess this was just an idea that came into my mind due to my misunderstanding of the ToT calculation.

>     * "global time definition is odd": This indeed is correct, mixing time with clock cycles is not a nice thing to do. :) So that line should actually read
>       ```c++
>       hits.emplace_back(pixel, time, pixel_charge.getGlobalTime() + std::get<2>(arrival), charge, &pixel_charge);
>       ```

Glad I'm not entirely stupid, I will open a PR to fix it :)

**Comment by simonspa** [comment]
The other option we have would be to provide also the global timestamp in ToA clock units - I think that would be a bit more consistent, no?

**Comment by stephanlachnit** [comment]
Hm, I'm not sure if that is more useful though. I've only used the global time once, and in this case the actual time was more useful than if it would be in clock cycles (with the DepositionReader, which made me realize I haven't set a time limit in Geant4 and it went 3 mil years in one step). I can imagine that the actual time is also more useful when having larger setups with different kinds of sensors (i.e. different clock speeds), but I no expert here so whatever you prefer.

**Comment by simonspa** [comment]
Agreed, let's leave that in absolute time then.
